export const banners = [
  {
    image: "",
    nome: "Banner Institucional",
    pagina: "Institucional",
    secao: "Banner Destaque",
    ordem: "--",
  },
  {
    image: "",
    nome: "Banner Corporativo",
    pagina: "Corporativo",
    secao: "Banner Destaque",
    ordem: "--",
  },
  {
    image: "",
    nome: "Sobre Nós",
    pagina: "Institucional",
    secao: "Conteúdo",
    ordem: "1",
  },
  {
    image: "",
    nome: "Imagem Conteúdo Institucional",
    pagina: "Institucional",
    secao: "Conteúdo",
    ordem: "2",
  },
  {
    image: "",
    nome: "Serviços e Parcerias",
    pagina: "Institucional",
    secao: "Conteúdo",
    ordem: "3",
  },
  {
    image: "",
    nome: "Aniversário",
    pagina: "Corporativo",
    secao: "Conteúdo",
    ordem: "4",
  },
  {
    image: "",
    nome: "Mídia em Tela",
    pagina: "Corporativo",
    secao: "Conteúdo",
    ordem: "5",
  },
  {
    image: "",
    nome: "Filme Transformers",
    pagina: "Início",
    secao: "Banner Destaque",
    ordem: "1",
  },
  {
    image: "",
    nome: "Filme A Menina e o Dragão",
    pagina: "Início",
    secao: "Banner Destaque",
    ordem: "2",
  },
  {
    image: "",
    nome: "Combo Coringa",
    pagina: "Início",
    secao: "Banner Destaque",
    ordem: "6",
  },
];
