export const filmes = [
  {
    capa: "",
    titulo: "Dragon Ball DAIMA",
    tituloEmIngles: "Dragon Ball DAIMA",
    cadastro: "25/11/2024",
    id: "1087",
    ordem: "1",
  },
  {
    capa: "",
    titulo: "Lilo & Stitch (2025)",
    tituloEmIngles: "Lilo & Stitch",
    cadastro: "25/11/2024",
    id: "1088",
    ordem: "2",
  },
  {
    capa: "",
    titulo: "Capitão América: Admirável Mundo Novo",
    tituloEmIngles: "Captain America: Brave New World",
    cadastro: "25/11/2024",
    id: "1090",
    ordem: "3",
  },
  {
    capa: "",
    titulo: "O maravilhoso mágico de Oz: parte 1",
    tituloEmIngles: "The wizard of Esmerald City",
    cadastro: "25/11/2024",
    id: "1091",
    ordem: "4",
  },
  {
    capa: "",
    titulo: "Ainda Estou Aqui",
    tituloEmIngles: "Ainda Estou Aqui",
    cadastro: "25/11/2024",
    id: "1092",
    ordem: "5",
  },
  {
    capa: "",
    titulo: "Acompanhante Perfeita",
    tituloEmIngles: "Companion",
    cadastro: "25/11/2024",
    id: "1093",
    ordem: "6",
  },
  {
    capa: "",
    titulo: "Blindado",
    tituloEmIngles: "Armor",
    cadastro: "25/11/2024",
    id: "1094",
    ordem: "7",
  },
  {
    capa: "",
    titulo: "Covil de Ladrões 2",
    tituloEmIngles: "Den of Thieves 2: Pantera",
    cadastro: "25/11/2024",
    id: "1095",
    ordem: "8",
  },
  {
    capa: "",
    titulo: "Conclave",
    tituloEmIngles: "Conclave",
    cadastro: "25/11/2024",
    id: "1096",
    ordem: "9",
  },
  {
    capa: "",
    titulo: "O Auto da Compadecida 2",
    tituloEmIngles: "O Auto da Compadecida 2",
    cadastro: "25/11/2024",
    id: "1097",
    ordem: "10",
  },
];
