export const unidades = [
  { value: "1", label: "CINESERCLA NORTE" },
  { value: "2", label: "CINESERCLA BIG" },
  { value: "3", label: "CINESERCLA GV" },
  { value: "4", label: "CINESERCLA TAMBIA" },
  { value: "5", label: "CINESERCLA CAMPINA GRANDE" },
  // { value: "6", label: "CINESERCLA ?" },
  { value: "7", label: "CINESERCLA PREMIO" },
  { value: "9", label: "CINESERCLA CAJAZEIRAS" },
  { value: "10", label: "CINESERCLA ITAGUAÍ" },
  { value: "11", label: "CINESERCLA NILÓPOLIS" },
  { value: "12", label: "CINESERCLA TEIXEIRA DE FREITAS" },
  { value: "13", label: "CINESERCLA MONTSERRAT" },
  { value: "14", label: "CINESERCLA OSASCO" },
  { value: "15", label: "CINESERCLA LINHARES" },
  // { value: "16", label: "CINESERCLA ?" },
  // { value: "17", label: "CINESERCLA ?" },
  { value: "18", label: "CINESERCLA SHOPPING AVENIDA" },
  // { value: "?", label: "CINESERCLA ARACAJU" },
  // { value: "?", label: "CINESERCLA JUSTINÓPOLIS" },
];
